version: '3.2'
services:
    php-apache:
        build:
          context: ./timeclock
        #image: php:7.2.1-apache
        ports:
            - "127.0.0.1:8000:80"
        volumes:
            - ./timeclock:/var/www/html
        links:
            - 'db'
    db:
      image: mysql:5.7
      volumes:
          - ./db:/var/lib/mysql
      environment:
          MYSQL_ROOT_PASSWORD: "rootpwd"
          MYSQL_USER: 'devuser'
          MYSQL_PASSWORD: 'devpass'
          MYSQL_DATABASE: 'timeclock'
    phpmyadmin:
      depends_on:
        - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
        - '127.0.0.1:8080:80'
      environment:
        PMA_HOST: db
volumes:
  db: