version: '3.2'
services:
    php-apache:
        depends_on:
            - db
        build:
          context: ./timeclock
        ports:
            - "127.0.0.1:80:80"
        volumes:
            - ./timeclock:/var/www/html
        links:
            - 'db'
    db:
      image: mysql:5.7
      volumes:
          - ./db:/var/lib/mysql
      environment:
          MYSQL_ROOT_PASSWORD: "rootpwd"
          MYSQL_USER: 'devuser'
          MYSQL_PASSWORD: 'devpass'
          MYSQL_DATABASE: 'timeclock'
#    phpmyadmin:
#      depends_on:
#        - db
#      image: phpmyadmin/phpmyadmin
#      container_name: phpmyadmin
 #     restart: always
  #    ports:
  #      - 80:80
  #    environment:
  #      PMA_HOST: db
volumes:
  db:
